name: 'scan-sign'
author: 'abook-presidio'
description: 'A module to Scan containers & code and then pass it on to notation CLI'

# env:
#   aws: "AWS"
#   azure: "AZURE"

inputs:
  # cloud provider 
  CLOUD:
    description: "The Cloud Provider being used [AWS | Azure]"
    required: true

  REPO:
    description: "The container repository URI"
    required: true
  
  # wiz items
  WIZ_CLIENT_ID:
    description: "Set the WIZ client id"
    required: true

  WIZ_CLIENT_SECRET:
    description: "Set the WIZ client secret"
    required: true

  ACCOUNT_ID:
    description: "The AWS account ID OR the Azure subscription ID"
    required: true

  # AWS credentials
  AWS_ACCESS:
    description: "Set the AWS access key"
    required: false
  
  AWS_SECRET:
    description: "Set the AWS secret key"
    required: false   

runs:
  using: "composite"
  steps:
    - name: Check Cloud Provider 
      if: ${{ inputs.CLOUD == 'AWS' }}
      run: echo -e "CLOUD is AWS"
      shell: bash

    - name: Check Cloud Provider2
      if: ${{ inputs.CLOUD != 'AWS' }}
      run: echo -e "CLOUD is AZURE"
      shell: bash

    - name: Download ECR Credential Helper
      if: ${{ inputs.CLOUD == 'AWS' }}
      run: |
          sudo apt update
          sudo apt install -y amazon-ecr-credential-helper
          cd ~/
          pwd
      shell: bash

    - name: Build Docker Image
      run: docker build . -t TEST_TAG
      shell: bash 

    - name: Download wiz-cli binary
      run: curl -o wizcli https://wizcli.app.wiz.io/latest/wizcli && chmod +x wizcli
      shell: bash

    - name: Authenticate to WIZ 
      run: ./wizcli auth --id ${{ inputs.WIZ_CLIENT_ID}} --secret ${{inputs.wiz_client_secret}}
      shell: bash

    - name: Scan Directory Secrets
      run: ./wizcli dir scan --path .  -p "Default secrets policy"
      shell: bash 

    - name: Scan Directory Vulnerabilties
      run: ./wizcli dir scan --path .  -p "Default vulnerabilities policy"
      shell: bash

    - name: Install notation cli
      shell: bash
      run: |
        sudo apt install -y /home/runner/work/securecontainer/securecontainer/aws-signer-notation-cli_amd64.deb


    